


language_selectors= [
{"value": "Acehnese (Arabic script)", "label": "Acehnese (Arabic script)"},
{"value": "Acehnese (Latin script)", "label": "Acehnese (Latin script)"},
{"value": "Mesopotamian Arabic", "label": "Mesopotamian Arabic"},
{"value": "Taizzi-Adeni Arabic", "label": "Taizzi-Adeni Arabic"},
{"value": "Tunisian Arabic", "label": "Tunisian Arabic"},
{"value": "Afrikaans", "label": "Afrikaans"},
{"value": "South Levantine Arabic", "label": "South Levantine Arabic"},
{"value": "Akan", "label": "Akan"},
{"value": "Amharic", "label": "Amharic"},
{"value": "North Levantine Arabic", "label": "North Levantine Arabic"},
{"value": "Modern Standard Arabic", "label": "Modern Standard Arabic"},
{"value": "Modern Standard Arabic (Romanized)", "label": "Modern Standard Arabic (Romanized)"},
{"value": "Najdi Arabic", "label": "Najdi Arabic"},
{"value": "Moroccan Arabic", "label": "Moroccan Arabic"},
{"value": "Egyptian Arabic", "label": "Egyptian Arabic"},
{"value": "Assamese", "label": "Assamese"},
{"value": "Asturian", "label": "Asturian"},
{"value": "Awadhi", "label": "Awadhi"},
{"value": "Central Aymara", "label": "Central Aymara"},
{"value": "South Azerbaijani", "label": "South Azerbaijani"},
{"value": "North Azerbaijani", "label": "North Azerbaijani"},
{"value": "Bashkir", "label": "Bashkir"},
{"value": "Bambara", "label": "Bambara"},
{"value": "Balinese", "label": "Balinese"},
{"value": "Belarusian", "label": "Belarusian"},
{"value": "Bemba", "label": "Bemba"},
{"value": "Bengali", "label": "Bengali"},
{"value": "Bhojpuri", "label": "Bhojpuri"},
{"value": "Banjar (Arabic script)", "label": "Banjar (Arabic script)"},
{"value": "Banjar (Latin script)", "label": "Banjar (Latin script)"},
{"value": "Standard Tibetan", "label": "Standard Tibetan"},
{"value": "Bosnian", "label": "Bosnian"},
{"value": "Buginese", "label": "Buginese"},
{"value": "Bulgarian", "label": "Bulgarian"},
{"value": "Catalan", "label": "Catalan"},
{"value": "Cebuano", "label": "Cebuano"},
{"value": "Czech", "label": "Czech"},
{"value": "Chokwe", "label": "Chokwe"},
{"value": "Central Kurdish", "label": "Central Kurdish"},
{"value": "Crimean Tatar", "label": "Crimean Tatar"},
{"value": "Welsh", "label": "Welsh"},
{"value": "Danish", "label": "Danish"},
{"value": "German", "label": "German"},
{"value": "Southwestern Dinka", "label": "Southwestern Dinka"},
{"value": "Dyula", "label": "Dyula"},
{"value": "Dzongkha", "label": "Dzongkha"},
{"value": "Greek", "label": "Greek"},
{"value": "English", "label": "English"},
{"value": "Esperanto", "label": "Esperanto"},
{"value": "Estonian", "label": "Estonian"},
{"value": "Basque", "label": "Basque"},
{"value": "Ewe", "label": "Ewe"},
{"value": "Faroese", "label": "Faroese"},
{"value": "Fijian", "label": "Fijian"},
{"value": "Finnish", "label": "Finnish"},
{"value": "Fon", "label": "Fon"},
{"value": "French", "label": "French"},
{"value": "Friulian", "label": "Friulian"},
{"value": "Nigerian Fulfulde", "label": "Nigerian Fulfulde"},
{"value": "Scottish Gaelic", "label": "Scottish Gaelic"},
{"value": "Irish", "label": "Irish"},
{"value": "Galician", "label": "Galician"},
{"value": "Guarani", "label": "Guarani"},
{"value": "Gujarati", "label": "Gujarati"},
{"value": "Haitian Creole", "label": "Haitian Creole"},
{"value": "Hausa", "label": "Hausa"},
{"value": "Hebrew", "label": "Hebrew"},
{"value": "Hindi", "label": "Hindi"},
{"value": "Chhattisgarhi", "label": "Chhattisgarhi"},
{"value": "Croatian", "label": "Croatian"},
{"value": "Hungarian", "label": "Hungarian"},
{"value": "Armenian", "label": "Armenian"},
{"value": "Igbo", "label": "Igbo"},
{"value": "Ilocano", "label": "Ilocano"},
{"value": "Indonesian", "label": "Indonesian"},
{"value": "Icelandic", "label": "Icelandic"},
{"value": "Italian", "label": "Italian"},
{"value": "Javanese", "label": "Javanese"},
{"value": "Japanese", "label": "Japanese"},
{"value": "Kabyle", "label": "Kabyle"},
{"value": "Jingpho", "label": "Jingpho"},
{"value": "Kamba", "label": "Kamba"},
{"value": "Kannada", "label": "Kannada"},
{"value": "Kashmiri (Arabic script)", "label": "Kashmiri (Arabic script)"},
{"value": "Kashmiri (Devanagari script)", "label": "Kashmiri (Devanagari script)"},
{"value": "Georgian", "label": "Georgian"},
{"value": "Central Kanuri (Arabic script)", "label": "Central Kanuri (Arabic script)"},
{"value": "Central Kanuri (Latin script)", "label": "Central Kanuri (Latin script)"},
{"value": "Kazakh", "label": "Kazakh"},
{"value": "Kabiyè", "label": "Kabiyè"},
{"value": "Kabuverdianu", "label": "Kabuverdianu"},
{"value": "Khmer", "label": "Khmer"},
{"value": "Kikuyu", "label": "Kikuyu"},
{"value": "Kinyarwanda", "label": "Kinyarwanda"},
{"value": "Kyrgyz", "label": "Kyrgyz"},
{"value": "Kimbundu", "label": "Kimbundu"},
{"value": "Northern Kurdish", "label": "Northern Kurdish"},
{"value": "Kikongo", "label": "Kikongo"},
{"value": "Korean", "label": "Korean"},
{"value": "Lao", "label": "Lao"},
{"value": "Ligurian", "label": "Ligurian"},
{"value": "Limburgish", "label": "Limburgish"},
{"value": "Lingala", "label": "Lingala"},
{"value": "Lithuanian", "label": "Lithuanian"},
{"value": "Lombard", "label": "Lombard"},
{"value": "Latgalian", "label": "Latgalian"},
{"value": "Luxembourgish", "label": "Luxembourgish"},
{"value": "Luba-Kasai", "label": "Luba-Kasai"},
{"value": "Ganda", "label": "Ganda"},
{"value": "Luo", "label": "Luo"},
{"value": "Mizo", "label": "Mizo"},
{"value": "Standard Latvian", "label": "Standard Latvian"},
{"value": "Magahi", "label": "Magahi"},
{"value": "Maithili", "label": "Maithili"},
{"value": "Malayalam", "label": "Malayalam"},
{"value": "Marathi", "label": "Marathi"},
{"value": "Minangkabau (Arabic script)", "label": "Minangkabau (Arabic script)"},
{"value": "Minangkabau (Latin script)", "label": "Minangkabau (Latin script)"},
{"value": "Macedonian", "label": "Macedonian"},
{"value": "Plateau Malagasy", "label": "Plateau Malagasy"},
{"value": "Maltese", "label": "Maltese"},
{"value": "Meitei (Bengali script)", "label": "Meitei (Bengali script)"},
{"value": "Halh Mongolian", "label": "Halh Mongolian"},
{"value": "Mossi", "label": "Mossi"},
{"value": "Maori", "label": "Maori"},
{"value": "Burmese", "label": "Burmese"},
{"value": "Dutch", "label": "Dutch"},
{"value": "Norwegian Nynorsk", "label": "Norwegian Nynorsk"},
{"value": "Norwegian Bokmål", "label": "Norwegian Bokmål"},
{"value": "Nepali", "label": "Nepali"},
{"value": "Northern Sotho", "label": "Northern Sotho"},
{"value": "Nuer", "label": "Nuer"},
{"value": "Nyanja", "label": "Nyanja"},
{"value": "Occitan", "label": "Occitan"},
{"value": "West Central Oromo", "label": "West Central Oromo"},
{"value": "Odia", "label": "Odia"},
{"value": "Pangasinan", "label": "Pangasinan"},
{"value": "Eastern Panjabi", "label": "Eastern Panjabi"},
{"value": "Papiamento", "label": "Papiamento"},
{"value": "Western Persian", "label": "Western Persian"},
{"value": "Polish", "label": "Polish"},
{"value": "Portuguese", "label": "Portuguese"},
{"value": "Dari", "label": "Dari"},
{"value": "Southern Pashto", "label": "Southern Pashto"},
{"value": "Ayacucho Quechua", "label": "Ayacucho Quechua"},
{"value": "Romanian", "label": "Romanian"},
{"value": "Rundi", "label": "Rundi"},
{"value": "Russian", "label": "Russian"},
{"value": "Sango", "label": "Sango"},
{"value": "Sanskrit", "label": "Sanskrit"},
{"value": "Santali", "label": "Santali"},
{"value": "Sicilian", "label": "Sicilian"},
{"value": "Shan", "label": "Shan"},
{"value": "Sinhala", "label": "Sinhala"},
{"value": "Slovak", "label": "Slovak"},
{"value": "Slovenian", "label": "Slovenian"},
{"value": "Samoan", "label": "Samoan"},
{"value": "Shona", "label": "Shona"},
{"value": "Sindhi", "label": "Sindhi"},
{"value": "Somali", "label": "Somali"},
{"value": "Southern Sotho", "label": "Southern Sotho"},
{"value": "Spanish", "label": "Spanish"},
{"value": "Tosk Albanian", "label": "Tosk Albanian"},
{"value": "Sardinian", "label": "Sardinian"},
{"value": "Serbian", "label": "Serbian"},
{"value": "Swati", "label": "Swati"},
{"value": "Sundanese", "label": "Sundanese"},
{"value": "Swedish", "label": "Swedish"},
{"value": "Swahili", "label": "Swahili"},
{"value": "Silesian", "label": "Silesian"},
{"value": "Tamil", "label": "Tamil"},
{"value": "Tatar", "label": "Tatar"},
{"value": "Telugu", "label": "Telugu"},
{"value": "Tajik", "label": "Tajik"},
{"value": "Tagalog", "label": "Tagalog"},
{"value": "Thai", "label": "Thai"},
{"value": "Tigrinya", "label": "Tigrinya"},
{"value": "Tamasheq (Latin script)", "label": "Tamasheq (Latin script)"},
{"value": "Tamasheq (Tifinagh script)", "label": "Tamasheq (Tifinagh script)"},
{"value": "Tok Pisin", "label": "Tok Pisin"},
{"value": "Tswana", "label": "Tswana"},
{"value": "Tsonga", "label": "Tsonga"},
{"value": "Turkish", "label": "Turkish"},
{"value": "Tulu", "label": "Tulu"},
{"value": "Central Atlas Tamazight (Latin script)", "label": "Central Atlas Tamazight (Latin script)"},
{"value": "Uighur", "label": "Uighur"},
{"value": "Ukrainian", "label": "Ukrainian"},
{"value": "Urdu", "label": "Urdu"},
{"value": "Uzbek", "label": "Uzbek"},
{"value": "Venda", "label": "Venda"},
{"value": "Vietnamese", "label": "Vietnamese"},
{"value": "Volapük", "label": "Volapük"},
{"value": "Votic", "label": "Votic"},
{"value": "Walloon", "label": "Walloon"},
{"value": "Wolof", "label": "Wolof"},
{"value": "Central Yupik", "label": "Central Yupik"},
{"value": "Yiddish", "label": "Yiddish"},
{"value": "Yoruba", "label": "Yoruba"},
{"value": "Zhuang", "label": "Zhuang"},
{"value": "Chinese (Simplified)", "label": "Chinese (Simplified)"},
{"value": "Chinese (Traditional)", "label": "Chinese (Traditional)"},
{"value": "Zulu", "label": "Zulu"},
]


language_codes = {
    'Acehnese (Arabic script)': 'ace_Arab',
    'Acehnese (Latin script)': 'ace_Latn',
    'Mesopotamian Arabic': 'acm_Arab',
    'Ta’izzi-Adeni Arabic': 'acq_Arab',
    'Tunisian Arabic': 'aeb_Arab',
    'Afrikaans': 'afr_Latn',
    'South Levantine Arabic': 'ajp_Arab',
    'Akan': 'aka_Latn',
    'Amharic': 'amh_Ethi',
    'North Levantine Arabic': 'apc_Arab',
    'Modern Standard Arabic': 'arb_Arab',
    'Modern Standard Arabic (Romanized)': 'arb_Latn',
    'Najdi Arabic': 'ars_Arab',
    'Moroccan Arabic': 'ary_Arab',
    'Egyptian Arabic': 'arz_Arab',
    'Assamese': 'asm_Beng',
    'Asturian': 'ast_Latn',
    'Awadhi': 'awa_Deva',
    'Central Aymara': 'ayr_Latn',
    'South Azerbaijani': 'azb_Arab',
    'North Azerbaijani': 'azj_Latn',
    'Bashkir': 'bak_Cyrl',
    'Bambara': 'bam_Latn',
    'Balinese': 'ban_Latn',
    'Belarusian': 'bel_Cyrl',
    'Bemba': 'bem_Latn',
    'Bengali': 'ben_Beng',
    'Bhojpuri': 'bho_Deva',
    'Banjar (Arabic script)': 'bjn_Arab',
    'Banjar (Latin script)': 'bjn_Latn',
    'Standard Tibetan': 'bod_Tibt',
    'Bosnian': 'bos_Latn',
    'Buginese': 'bug_Latn',
    'Bulgarian': 'bul_Cyrl',
    'Catalan': 'cat_Latn',
    'Cebuano': 'ceb_Latn',
    'Czech': 'ces_Latn',
    'Chokwe': 'cjk_Latn',
    'Central Kurdish': 'ckb_Arab',
    'Crimean Tatar': 'crh_Latn',
    'Welsh': 'cym_Latn',
    'Danish': 'dan_Latn',
    'German': 'deu_Latn',
    'Southwestern Dinka': 'dik_Latn',
    'Dyula': 'dyu_Latn',
    'Dzongkha': 'dzo_Tibt',
    'Greek': 'ell_Grek',
    'English': 'eng_Latn',
    'Esperanto': 'epo_Latn',
    'Estonian': 'est_Latn',
    'Basque': 'eus_Latn',
    'Ewe': 'ewe_Latn',
    'Faroese': 'fao_Latn',
    'Fijian': 'fij_Latn',
    'Finnish': 'fin_Latn',
    'Fon': 'fon_Latn',
    'French': 'fra_Latn',
    'Friulian': 'fur_Latn',
    'Nigerian Fulfulde': 'fuv_Latn',
    'Scottish Gaelic': 'gla_Latn',
    'Irish': 'gle_Latn',
    'Galician': 'glg_Latn',
    'Guarani': 'grn_Latn',
    'Gujarati': 'guj_Gujr',
    'Haitian Creole': 'hat_Latn',
    'Hausa': 'hau_Latn',
    'Hebrew': 'heb_Hebr',
    'Hindi': 'hin_Deva',
    'Chhattisgarhi': 'hne_Deva',
    'Croatian': 'hrv_Latn',
    'Hungarian': 'hun_Latn',
    'Armenian': 'hye_Armn',
    'Igbo': 'ibo_Latn',
    'Ilocano': 'ilo_Latn',
    'Indonesian': 'ind_Latn',
    'Icelandic': 'isl_Latn',
    'Italian': 'ita_Latn',
    'Javanese': 'jav_Latn',
    'Japanese': 'jpn_Jpan',
    'Kabyle': 'kab_Latn',
    'Jingpho': 'kac_Latn',
    'Kamba': 'kam_Latn',
    'Kannada': 'kan_Knda',
    'Kashmiri (Arabic script)': 'kas_Arab',
    'Kashmiri (Devanagari script)': 'kas_Deva',
    'Georgian': 'kat_Geor',
    'Central Kanuri (Arabic script)': 'knc_Arab',
    'Central Kanuri (Latin script)': 'knc_Latn',
    'Kazakh': 'kaz_Cyrl',
    'Kabiyè': 'kbp_Latn',
    'Kabuverdianu': 'kea_Latn',
    'Khmer': 'khm_Khmr',
    'Kikuyu': 'kik_Latn',
    'Kinyarwanda': 'kin_Latn',
    'Kyrgyz': 'kir_Cyrl',
    'Kimbundu': 'kmb_Latn',
    'Northern Kurdish': 'kmr_Latn',
    'Kikongo': 'kon_Latn',
    'Korean': 'kor_Hang',
    'Lao': 'lao_Laoo',
    'Ligurian': 'lij_Latn',
    'Limburgish': 'lim_Latn',
    'Lingala': 'lin_Latn',
    'Lithuanian': 'lit_Latn',
    'Lombard': 'lmo_Latn',
    'Latgalian': 'ltg_Latn',
    'Luxembourgish': 'ltz_Latn',
    'Luba-Kasai': 'lua_Latn',
    'Ganda': 'lug_Latn',
    'Luo': 'luo_Latn',
    'Mizo': 'lus_Latn',
    'Standard Latvian': 'lvs_Latn',
    'Magahi': 'mag_Deva',
    'Maithili': 'mai_Deva',
    'Malayalam': 'mal_Mlym',
    'Marathi': 'mar_Deva',
    'Minangkabau (Arabic script)': 'min_Arab',
    'Minangkabau (Latin script)': 'min_Latn',
    'Macedonian': 'mkd_Cyrl',
    'Plateau Malagasy': 'plt_Latn',
    'Maltese': 'mlt_Latn',
    'Meitei (Bengali script)': 'mni_Beng',
    'Halh Mongolian': 'khk_Cyrl',
    'Mossi': 'mos_Latn',
    'Maori': 'mri_Latn',
    'Burmese': 'mya_Mymr',
    'Dutch': 'nld_Latn',
    'Norwegian Nynorsk': 'nno_Latn',
    'Norwegian Bokmål': 'nob_Latn',
    'Nepali': 'npi_Deva',
    'Northern Sotho': 'nso_Latn',
    'Nuer': 'nus_Latn',
    'Nyanja': 'nya_Latn',
    'Occitan': 'oci_Latn',
    'West Central Oromo': 'gaz_Latn',
    'Odia': 'ory_Orya',
    'Pangasinan': 'pag_Latn',
    'Eastern Panjabi': 'pan_Guru',
    'Papiamento': 'pap_Latn',
    'Western Persian': 'pes_Arab',
    'Polish': 'pol_Latn',
    'Portuguese': 'por_Latn',
    'Dari': 'prs_Arab',
    'Southern Pashto': 'pbt_Arab',
    'Ayacucho Quechua': 'quy_Latn',
    'Romanian': 'ron_Latn',
    'Rundi': 'run_Latn',
    'Russian': 'rus_Cyrl',
    'Sango': 'sag_Latn',
    'Sanskrit': 'san_Deva',
    'Santali': 'sat_Olck',
    'Sicilian': 'scn_Latn',
    'Shan': 'shn_Mymr',
    'Sinhala': 'sin_Sinh',
    'Slovak': 'slk_Latn',
    'Slovenian': 'slv_Latn',
    'Samoan': 'smo_Latn',
    'Shona': 'sna_Latn',
    'Sindhi': 'snd_Arab',
    'Somali': 'som_Latn',
    'Southern Sotho': 'sot_Latn',
    'Spanish': 'spa_Latn',
    'Tosk Albanian': 'als_Latn',
    'Sardinian': 'srd_Latn',
    'Serbian': 'srp_Cyrl',
    'Swati': 'ssw_Latn',
    'Sundanese': 'sun_Latn',
    'Swedish': 'swe_Latn',
    'Swahili': 'swh_Latn',
    'Silesian': 'szl_Latn',
    'Tamil': 'tam_Taml',
    'Tatar': 'tat_Cyrl',
    'Telugu': 'tel_Telu',
    'Tajik': 'tgk_Cyrl',
    'Tagalog': 'tgl_Latn',
    'Thai': 'tha_Thai',
    'Tigrinya': 'tir_Ethi',
    'Tamasheq (Latin script)': 'taq_Latn',
    'Tamasheq (Tifinagh script)': 'taq_Tfng',
    'Tok Pisin': 'tpi_Latn',
    'Tswana': 'tsn_Latn',
    'Tsonga': 'tso_Latn',
    'Turkish': 'tur_Latn',
    'Tulu': 'tcy_Tulu',
    'Central Atlas Tamazight (Latin script)': 'tzm_Latn',
    'Uighur': 'uig_Arab',
    'Ukrainian': 'ukr_Cyrl',
    'Urdu': 'urd_Arab',
    'Uzbek': 'uzb_Cyrl',
    'Venda': 'ven_Latn',
    'Vietnamese': 'vie_Latn',
    'Volapük': 'vol_Latn',
    'Votic': 'vot_Latn',
    'Walloon': 'wln_Latn',
    'Wolof': 'wol_Latn',
    'Central Yupik': 'esu_Latn',
    'Yiddish': 'yid_Hebr',
    'Yoruba': 'yor_Latn',
    'Zhuang': 'zha_Latn',
    'Chinese (Simplified)': 'zho_Hans',
    'Chinese (Traditional)': 'zho_Hant',
    'Zulu': 'zul_Latn'
}